// Code generated by protoc-gen-go. DO NOT EDIT.
// source: objstore.proto

package objstore

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// An request to create a bucket
type CreateBucketRequest struct {
	// The bucket name
	BucketName           string   `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBucketRequest) Reset()         { *m = CreateBucketRequest{} }
func (m *CreateBucketRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBucketRequest) ProtoMessage()    {}
func (*CreateBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f33983deb7d278a, []int{0}
}

func (m *CreateBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBucketRequest.Unmarshal(m, b)
}
func (m *CreateBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBucketRequest.Marshal(b, m, deterministic)
}
func (m *CreateBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBucketRequest.Merge(m, src)
}
func (m *CreateBucketRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBucketRequest.Size(m)
}
func (m *CreateBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBucketRequest proto.InternalMessageInfo

func (m *CreateBucketRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

// An request to list a bucket
type ListBucketRequest struct {
	// The bucket name
	BucketName           string   `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBucketRequest) Reset()         { *m = ListBucketRequest{} }
func (m *ListBucketRequest) String() string { return proto.CompactTextString(m) }
func (*ListBucketRequest) ProtoMessage()    {}
func (*ListBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f33983deb7d278a, []int{1}
}

func (m *ListBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBucketRequest.Unmarshal(m, b)
}
func (m *ListBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBucketRequest.Marshal(b, m, deterministic)
}
func (m *ListBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBucketRequest.Merge(m, src)
}
func (m *ListBucketRequest) XXX_Size() int {
	return xxx_messageInfo_ListBucketRequest.Size(m)
}
func (m *ListBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBucketRequest proto.InternalMessageInfo

func (m *ListBucketRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

// An response to ListBucketRequest
type ListBucketResponse struct {
	// Zero or more object names
	ObjectName           []string `protobuf:"bytes,1,rep,name=objectName,proto3" json:"objectName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBucketResponse) Reset()         { *m = ListBucketResponse{} }
func (m *ListBucketResponse) String() string { return proto.CompactTextString(m) }
func (*ListBucketResponse) ProtoMessage()    {}
func (*ListBucketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f33983deb7d278a, []int{2}
}

func (m *ListBucketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBucketResponse.Unmarshal(m, b)
}
func (m *ListBucketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBucketResponse.Marshal(b, m, deterministic)
}
func (m *ListBucketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBucketResponse.Merge(m, src)
}
func (m *ListBucketResponse) XXX_Size() int {
	return xxx_messageInfo_ListBucketResponse.Size(m)
}
func (m *ListBucketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBucketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBucketResponse proto.InternalMessageInfo

func (m *ListBucketResponse) GetObjectName() []string {
	if m != nil {
		return m.ObjectName
	}
	return nil
}

// An request to get an object
type GetRequest struct {
	// The bucket name
	BucketName string `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	// The object name
	ObjectName           string   `protobuf:"bytes,2,opt,name=objectName,proto3" json:"objectName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f33983deb7d278a, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *GetRequest) GetObjectName() string {
	if m != nil {
		return m.ObjectName
	}
	return ""
}

// An response to GetRequest
type GetResponse struct {
	// The object data
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f33983deb7d278a, []int{4}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// An request to put an object
type PutRequest struct {
	// The bucket name
	BucketName string `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	// The object name
	ObjectName string `protobuf:"bytes,2,opt,name=objectName,proto3" json:"objectName,omitempty"`
	// The object data to be put
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f33983deb7d278a, []int{5}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *PutRequest) GetObjectName() string {
	if m != nil {
		return m.ObjectName
	}
	return ""
}

func (m *PutRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// An request to delete a bucket
type DeleteBucketRequest struct {
	// The bucket name
	BucketName           string   `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBucketRequest) Reset()         { *m = DeleteBucketRequest{} }
func (m *DeleteBucketRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBucketRequest) ProtoMessage()    {}
func (*DeleteBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f33983deb7d278a, []int{6}
}

func (m *DeleteBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBucketRequest.Unmarshal(m, b)
}
func (m *DeleteBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBucketRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBucketRequest.Merge(m, src)
}
func (m *DeleteBucketRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBucketRequest.Size(m)
}
func (m *DeleteBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBucketRequest proto.InternalMessageInfo

func (m *DeleteBucketRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

// An request to delete an object
type DeleteRequest struct {
	// The bucket name
	BucketName string `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	// The object name
	ObjectName           string   `protobuf:"bytes,2,opt,name=objectName,proto3" json:"objectName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f33983deb7d278a, []int{7}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *DeleteRequest) GetObjectName() string {
	if m != nil {
		return m.ObjectName
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateBucketRequest)(nil), "objstore.CreateBucketRequest")
	proto.RegisterType((*ListBucketRequest)(nil), "objstore.ListBucketRequest")
	proto.RegisterType((*ListBucketResponse)(nil), "objstore.ListBucketResponse")
	proto.RegisterType((*GetRequest)(nil), "objstore.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "objstore.GetResponse")
	proto.RegisterType((*PutRequest)(nil), "objstore.PutRequest")
	proto.RegisterType((*DeleteBucketRequest)(nil), "objstore.DeleteBucketRequest")
	proto.RegisterType((*DeleteRequest)(nil), "objstore.DeleteRequest")
}

func init() { proto.RegisterFile("objstore.proto", fileDescriptor_6f33983deb7d278a) }

var fileDescriptor_6f33983deb7d278a = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xcd, 0x4e, 0xbb, 0x40,
	0x14, 0xc5, 0xdb, 0x3f, 0xff, 0x34, 0x7a, 0x5b, 0x4d, 0xbc, 0xf5, 0x2b, 0x54, 0x8d, 0xce, 0xca,
	0x15, 0x4d, 0x6c, 0x59, 0xb9, 0xf3, 0x23, 0xc4, 0xa4, 0xb1, 0x06, 0x5f, 0x40, 0xa0, 0x57, 0x62,
	0xa5, 0x0e, 0xc2, 0xb0, 0xf0, 0x3d, 0x7c, 0x60, 0xc3, 0x4c, 0x80, 0x11, 0x49, 0xb5, 0x49, 0x77,
	0xcc, 0x19, 0xce, 0x3d, 0x27, 0x77, 0x7e, 0xb0, 0xcd, 0xfd, 0x79, 0x2a, 0x78, 0x42, 0x56, 0x9c,
	0x70, 0xc1, 0x71, 0xa3, 0x38, 0x9b, 0x83, 0x90, 0xf3, 0x30, 0xa2, 0xa1, 0xd4, 0xfd, 0xec, 0x79,
	0x48, 0x8b, 0x58, 0x7c, 0xa8, 0xdf, 0x98, 0x0d, 0xfd, 0xeb, 0x84, 0x3c, 0x41, 0x57, 0x59, 0xf0,
	0x4a, 0xc2, 0xa5, 0xf7, 0x8c, 0x52, 0x81, 0x27, 0x00, 0xbe, 0x14, 0xee, 0xbd, 0x05, 0x1d, 0xb6,
	0x4f, 0xdb, 0xe7, 0x9b, 0xae, 0xa6, 0xb0, 0x11, 0xec, 0x4c, 0x5e, 0x52, 0xb1, 0x9a, 0x69, 0x0c,
	0xa8, 0x9b, 0xd2, 0x98, 0xbf, 0xa5, 0x94, 0xbb, 0xb8, 0x3f, 0xa7, 0xa0, 0x70, 0x19, 0xb9, 0xab,
	0x52, 0xd8, 0x04, 0xc0, 0xf9, 0x73, 0x46, 0x6d, 0xda, 0x3f, 0x75, 0xaf, 0x4d, 0x3b, 0x83, 0xae,
	0xa3, 0x85, 0x23, 0xfc, 0x9f, 0x79, 0xc2, 0x93, 0x83, 0x7a, 0xae, 0xfc, 0x66, 0x4f, 0x00, 0x0f,
	0xd9, 0xba, 0x02, 0xcb, 0x04, 0x43, 0x4b, 0xb0, 0xa1, 0x7f, 0x43, 0x11, 0xad, 0xba, 0xf4, 0x29,
	0x6c, 0x29, 0xdb, 0x9a, 0xba, 0x5d, 0x7c, 0x1a, 0xd0, 0x9d, 0xca, 0xe3, 0x63, 0x4e, 0x0a, 0x3a,
	0xd0, 0x0b, 0x34, 0x18, 0xf0, 0xd8, 0x2a, 0xa1, 0x6a, 0x80, 0xc4, 0xdc, 0xb7, 0x14, 0x59, 0x56,
	0x41, 0x96, 0x75, 0x9b, 0x93, 0xc5, 0x5a, 0x78, 0x07, 0x10, 0x95, 0x2f, 0x8d, 0x83, 0x6a, 0xcc,
	0x0f, 0x68, 0xcc, 0xa3, 0xe6, 0x4b, 0xf5, 0x3e, 0xac, 0x95, 0x77, 0x9a, 0x69, 0xbb, 0xd2, 0x3b,
	0x35, 0xec, 0x70, 0x49, 0xa7, 0x31, 0x18, 0x21, 0x09, 0xdc, 0xad, 0xfc, 0x15, 0x56, 0xe6, 0x5e,
	0x4d, 0x2d, 0xe3, 0x6d, 0x30, 0xe2, 0xec, 0x9b, 0xab, 0x62, 0x63, 0x49, 0xd8, 0x25, 0x74, 0x54,
	0x6b, 0x3c, 0xa8, 0xf7, 0xfd, 0xd5, 0xec, 0x77, 0xa4, 0x32, 0xfa, 0x0a, 0x00, 0x00, 0xff, 0xff,
	0xbc, 0xc1, 0x20, 0x43, 0xd3, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ObjectStoreClient is the client API for ObjectStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ObjectStoreClient interface {
	// Create a bucket
	CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// List the names of all objects in a bucket
	ListBucket(ctx context.Context, in *ListBucketRequest, opts ...grpc.CallOption) (*ListBucketResponse, error)
	// Delete a bucket
	DeleteBucket(ctx context.Context, in *DeleteBucketRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Get an object in a bucket
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Put an object in a bucket
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Delete an object in a bucket
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type objectStoreClient struct {
	cc *grpc.ClientConn
}

func NewObjectStoreClient(cc *grpc.ClientConn) ObjectStoreClient {
	return &objectStoreClient{cc}
}

func (c *objectStoreClient) CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/objstore.ObjectStore/createBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) ListBucket(ctx context.Context, in *ListBucketRequest, opts ...grpc.CallOption) (*ListBucketResponse, error) {
	out := new(ListBucketResponse)
	err := c.cc.Invoke(ctx, "/objstore.ObjectStore/listBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) DeleteBucket(ctx context.Context, in *DeleteBucketRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/objstore.ObjectStore/deleteBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/objstore.ObjectStore/get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/objstore.ObjectStore/put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStoreClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/objstore.ObjectStore/delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectStoreServer is the server API for ObjectStore service.
type ObjectStoreServer interface {
	// Create a bucket
	CreateBucket(context.Context, *CreateBucketRequest) (*empty.Empty, error)
	// List the names of all objects in a bucket
	ListBucket(context.Context, *ListBucketRequest) (*ListBucketResponse, error)
	// Delete a bucket
	DeleteBucket(context.Context, *DeleteBucketRequest) (*empty.Empty, error)
	// Get an object in a bucket
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Put an object in a bucket
	Put(context.Context, *PutRequest) (*empty.Empty, error)
	// Delete an object in a bucket
	Delete(context.Context, *DeleteRequest) (*empty.Empty, error)
}

// UnimplementedObjectStoreServer can be embedded to have forward compatible implementations.
type UnimplementedObjectStoreServer struct {
}

func (*UnimplementedObjectStoreServer) CreateBucket(ctx context.Context, req *CreateBucketRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBucket not implemented")
}
func (*UnimplementedObjectStoreServer) ListBucket(ctx context.Context, req *ListBucketRequest) (*ListBucketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBucket not implemented")
}
func (*UnimplementedObjectStoreServer) DeleteBucket(ctx context.Context, req *DeleteBucketRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBucket not implemented")
}
func (*UnimplementedObjectStoreServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedObjectStoreServer) Put(ctx context.Context, req *PutRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (*UnimplementedObjectStoreServer) Delete(ctx context.Context, req *DeleteRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterObjectStoreServer(s *grpc.Server, srv ObjectStoreServer) {
	s.RegisterService(&_ObjectStore_serviceDesc, srv)
}

func _ObjectStore_CreateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).CreateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objstore.ObjectStore/CreateBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).CreateBucket(ctx, req.(*CreateBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_ListBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).ListBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objstore.ObjectStore/ListBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).ListBucket(ctx, req.(*ListBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_DeleteBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).DeleteBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objstore.ObjectStore/DeleteBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).DeleteBucket(ctx, req.(*DeleteBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objstore.ObjectStore/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objstore.ObjectStore/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/objstore.ObjectStore/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStoreServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ObjectStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "objstore.ObjectStore",
	HandlerType: (*ObjectStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createBucket",
			Handler:    _ObjectStore_CreateBucket_Handler,
		},
		{
			MethodName: "listBucket",
			Handler:    _ObjectStore_ListBucket_Handler,
		},
		{
			MethodName: "deleteBucket",
			Handler:    _ObjectStore_DeleteBucket_Handler,
		},
		{
			MethodName: "get",
			Handler:    _ObjectStore_Get_Handler,
		},
		{
			MethodName: "put",
			Handler:    _ObjectStore_Put_Handler,
		},
		{
			MethodName: "delete",
			Handler:    _ObjectStore_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "objstore.proto",
}
