# This provider will be used by srk commands unless specifically overwritten
default-provider : "aws"

# A provider is a complete set of services that all work together. Typically, a
# provider will have one implementation of each service category (although it
# is possible to omit service categories of they are not needed)
providers :
  lambci :
    faas : "lambciLambda"
  aws :
    faas : "awsLambda"
    objStore : "s3"
  local :
    faas : "openLambda"
    objStore : "filesystem"

# This configures each individual service implementation by category. The format is:
# service.CATEGORY.IMPLEMENTATION (e.g. service.faas.openLambda). These can be
# referenced in provider descriptions.
service :
  # Function as a Service
  faas :
    openLambda :
      # Path to the compiled openLambda manager command
      # e.g. ~/open-lambda/ol
      olcmd : null 
      # Path to the initialized open-lambda working directory
      # e.g. ~/open-lambda/default-ol/
      oldir : null
      # List of servers to send requests to
      olservers : [ "http://localhost:5000" ]
    awsLambda :
      # Your arn role.
      # e.g. `arn:aws:iam::123459789012:role/service-role/my-service-role-ae04d032`
      role : null
      # Optional vpc/security-group setup to use.
      # e.g.: "vpc-123456789abcdef,sg-123456789abcdef"
      vpc-config : null
      # Optional custom runtime and layer configuration
      runtimes :
        # example custom runtime definition
        cffs-python :
          # AWS runtime as base, use 'provided' for none
          base : provided
          # list of additional layers
          layers :
            - 'arn:aws:lambda:eu-central-1:669282166790:layer:runtime-python37:3'
      # Optional default runtime if runtime is not provided by CLI
      default-runtime : 'python3.7'
    lambciLambda:
      # optional remote configuration
      # if set the path values below are bound to the specified host
      remote:
        # path to scp command
        scp : '/usr/bin/scp'
        # path to ssh command
        ssh : '/usr/bin/ssh'
        # IP or hostname of server running the lambci/lambda docker image
        host : 'ec2-instance'
        # user for scp + ssh
        user : 'ubuntu'
        # key file for scp + ssh
        pem : '~/.aws/AWS.pem'
      # address of lambci server API
      address : 'localhost:9001'
      # path to the lambci directory - the following sub directories will be used:
      # * task    directory of lambda function
      # * runtime directory of the lambda runtime
      # * layers  directory of layer pool with each layer a sub directory
      # * env     environment file for lambci docker container
      directory : '~/lambci'
      # runtime configuration
      runtimes :
        # example runtime definition
        cffs-python :
          # list of layers that make up the runtime
          layers :
            - 'runtime-python37-1'
      # optional default runtime if runtime is not provided by CLI
      default-runtime : 'cffs-python'
    global:
